GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/6668709bbcd77400469261ae

###
GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Ignacio Fernández",
  "number": "011-68837680"
}

### Bad request
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Ignacio Fernández"
}

###
DELETE http://localhost:3001/api/persons/6660b47677caee913df4c571